In [3]:
from numpy import *
a = arange(100)
set_printoptions(threshold=10)
print a

[ 0  1  2 ..., 97 98 99]


In [9]:
# element wise operations 
a = array([20, 30, 40, 50])
b = arange(4)
c = a - b
print a
print b
print c

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]


In [6]:
print b**2

[0 1 4 9]


In [7]:
10 * sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [8]:
a < 35

array([ True,  True, False, False], dtype=bool)

In [10]:
# matrix operation
A = array([1,1])
B = array([2,3])
print A * B
print dot(A, B)

[2 3]
5


In [12]:
A = array([[1,2],[3,4]])
B = ones(4).reshape((2,2))
print A * B
print dot(A, B)

[[ 1.  2.]
 [ 3.  4.]]
[[ 3.  3.]
 [ 7.  7.]]


In [13]:
#calcurate and institute
A += B
print A
B *= A
print B

[[2 3]
 [4 5]]
[[ 2.  3.]
 [ 4.  5.]]


In [16]:
A = array([[2,3],[4,5]])
B = ones(4).reshape((2,2)) * 3.33333
A += B # B is converted to integer type because institute to int-type array A
print A

[[5 6]
 [7 8]]


In [18]:
# result type will be more precise one
a = ones(3, dtype=int32)
b = ones(3, dtype=int64)
c = a - b
print c.dtype.name

int64


In [19]:
# unary operations (単功)
a = random.random([2,3])
print a
print a.sum()
print a.min()
print a.max()

[[ 0.26434859  0.10870968  0.90047424]
 [ 0.48358017  0.09227217  0.4197822 ]]
2.26916704966
0.0922721678921
0.900474238961


In [20]:
# specifing axis
print a.sum(axis=0) # axis=0 : 2 of (2,3)
print a.sum(axis=1) # axis=1 : 3 of (2,3)

[ 0.74792876  0.20098185  1.32025644]
[ 1.27353251  0.99563454]


In [21]:
# cumulative sum
a = ones((3,4))
print a.cumsum()
print a.cumsum(axis=0)
print a.cumsum(axis=1)

[  1.   2.   3. ...,  10.  11.  12.]
[[ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]]
[[ 1.  2.  3.  4.]
 [ 1.  2.  3.  4.]
 [ 1.  2.  3.  4.]]


In [22]:
# Universal function (sin, cos, exp, etc...)
B = arange(3)
print exp(B)
print sqrt(B)
C = array([2., -1., 4.])
print add(B, C)

[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]
[ 2.  0.  6.]


In [23]:
# index, slice, iterating
# one-dimensional
a = arange(10)**3
print a[2]
print a[2:3]
a[:6:2] = -1 # equals a[0:6:2:] = -1 0から6まで2個間隔
print a
print a[::-1] # equals a[0:10:-1], reversed a

8
[8]
[ -1   1  -1  27  -1 125 216 343 512 729]
[729 512 343 216 125  -1  27  -1   1  -1]


In [28]:
a = arange(10)**3
a[5:0:1] = 3
print a
a[0:5:-1] = 1
print a
a[5:0:-1] = 2 #  変な感じになるから使わない方が良さそう
print a
a[0:5:1] = 3
print a

[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]
[  0   2   2   2   2   2 216 343 512 729]
[  3   3   3   3   3   2 216 343 512 729]


In [33]:
# Multidimensional
# fromfunction - create matrix like M(f(i,j)) : 座標から関数使って数値を作る
b = fromfunction(lambda i,j: 10*i+j, (5,4), dtype=int)
print b
print b[2,3]
print b[0:3,1]
print b[:, 1]
print b[1:3,:]
print b[-1] # equal to b[-1,:]

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[40 41 42 43]


In [36]:
# using dot(...) instead of colom
c = arange(27).reshape((3,3,3))
print c
print c[1,:,:]
print c[1,...]
print c[...,2]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]


In [37]:
# iteration
b = arange(9).reshape((3,3))
for row in b:
    print row
for elem in b.flat:
    print elem,

[0 1 2]
[3 4 5]
[6 7 8]
0 1 2 3 4 5 6 7 8


In [41]:
#shape manipulation
a = floor(10*random.random((3,4)))
print a.shape
print a
print a.ravel() # flatten
print a.transpose()

(3, 4)
[[ 5.  7.  9.  3.]
 [ 4.  1.  8.  3.]
 [ 8.  7.  8.  6.]]
[ 5.  7.  9. ...,  7.  8.  6.]
[[ 5.  4.  8.]
 [ 7.  1.  7.]
 [ 9.  8.  8.]
 [ 3.  3.  6.]]


In [45]:
print a.reshape(2, -1) # aは変更無し
print a
a.resize(2, 6) # a自体のサイズが変わる
print a

[[ 5.  7.  9.  3.  4.  1.]
 [ 8.  3.  8.  7.  8.  6.]]
[[ 5.  7.  9.  3.]
 [ 4.  1.  8.  3.]
 [ 8.  7.  8.  6.]]
[[ 5.  7.  9.  3.  4.  1.]
 [ 8.  3.  8.  7.  8.  6.]]


In [50]:
# stacking
a = floor(10*random.random((2,2)))
b = floor(10*random.random((2,2)))
print vstack((a,b)) # vertically stack
print hstack((a,b)) # horizonally stack
print column_stack((a,b)) # equals hstack

[[ 9.  3.]
 [ 1.  1.]
 [ 6.  9.]
 [ 7.  0.]]
[[ 9.  3.  6.  9.]
 [ 1.  1.  7.  0.]]
[[ 9.  3.  6.  9.]
 [ 1.  1.  7.  0.]]


In [56]:
# newaxis
a = array([4,2])
b = array([3,8])
print a[:,newaxis] # to 2D columns vector
print column_stack((a[:,newaxis],b[:,newaxis])) # hstack
print row_stack((a,b)) # vstack

[[4]
 [2]]
[[4 3]
 [2 8]]
[[4 2]
 [3 8]]


In [60]:
# convenient function
print r_[1:4,0,4] # this looks convenient to add the bias term
print r_[a,b]
print c_[1:3,4:6]

[1 2 3 0 4]
[4 2 3 8]
[[1 4]
 [2 5]]


In [61]:
# splitting array -> list of maller arrays
a = floor(10*random.random((2,12)))
print hsplit(a,3)
print hsplit(a,(3,4)) # splitするcolumnの位置を渡している
print hsplit(a,(2,5,7,10))

[array([[ 9.,  9.,  6.,  5.],
       [ 8.,  8.,  6.,  9.]]), array([[ 8.,  6.,  2.,  5.],
       [ 8.,  2.,  5.,  8.]]), array([[ 5.,  5.,  4.,  1.],
       [ 0.,  7.,  1.,  9.]])]
[array([[ 9.,  9.,  6.],
       [ 8.,  8.,  6.]]), array([[ 5.],
       [ 9.]]), array([[ 8.,  6.,  2., ...,  5.,  4.,  1.],
       [ 8.,  2.,  5., ...,  7.,  1.,  9.]])]
[array([[ 9.,  9.],
       [ 8.,  8.]]), array([[ 6.,  5.,  8.],
       [ 6.,  9.,  8.]]), array([[ 6.,  2.],
       [ 2.,  5.]]), array([[ 5.,  5.,  5.],
       [ 8.,  0.,  7.]]), array([[ 4.,  1.],
       [ 1.,  9.]])]


In [62]:
# copy and view
a = arange(12)
b = a
print b is a
print a
b.shape = 3,4 # a is also changed
print a

True
[ 0  1  2 ...,  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [63]:
# view : sharrow copy
c = a.view()
print c is a
print c.flags.owndata
c.shape = 2,6 # shapeは変わらない
print a.shape
c[0,4] = 1234 # 値は代入するともとの方も変わる 
print a

False
False
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [64]:
# slice is a view
s = a[:,1:3]
print a
print s
s[:] = 10
print a

[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


In [65]:
# deep copy
d = a.copy()
print d is a
d[0,0] = 9999
print a

False
[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


In [68]:
# array creation method
print eye(2,2)
print eye(2,2,dtype=int)

[[ 1.  0.]
 [ 0.  1.]]
[[1 0]
 [0 1]]


In [69]:
# *_like create matrix same shape as input
a = arange(12).reshape(3,4)
print zeros_like(a)
print empty_like(a)
print ones_like(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[ 5764607523034234880 -1152912731257411477                    6
                     0]
 [                   0                    0                    0
                     0]
 [                   0                    0                    0
      1688849860263936]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [71]:
# logspace
print logspace(-2,3,num=6)
print logspace(-2,3,num=7)

[  1.00000000e-02   1.00000000e-01   1.00000000e+00   1.00000000e+01
   1.00000000e+02   1.00000000e+03]
[  1.00000000e-02   6.81292069e-02   4.64158883e-01   3.16227766e+00
   2.15443469e+01   1.46779927e+02   1.00000000e+03]


In [80]:
# mgrid
m = mgrid[1:3,2:5] # x-value 1,2, y-value 1,2,3 のグリッド
print m.shape
print m
print m[:,1,2] # 最初を : にして、x,yの番号を指定してとりだす

(2, 2, 3)
[[[1 1 1]
  [2 2 2]]

 [[2 3 4]
  [2 3 4]]]
[2 4]


In [82]:
# ogrid
x, y = ogrid[0:3,0:3] # broadcasting rules で使用するらしいがよく分からん
print x
print y
print x*y

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 0 0]
 [0 1 2]
 [0 2 4]]


In [86]:
# logical
a = array((True, False, True))
print a.any()
print a.all()
# flags
a = array([0,1,2,3,4])
print a.nonzero()
b = array([3,4,5,6,7])
c = array([-1,-2,-3,-4,-5])
print where(a < 3, b, c) # 条件を満たすindex => b, otherwise c
indices = where(a<3)
print indices
print b[indices]

True
False
(array([1, 2, 3, 4]),)
[ 3  4  5 -4 -5]
(array([0, 1, 2]),)
[3 4 5]


In [93]:
# take
a = array([10,20,30,40])
print a.take([0,0,3])
print a[[0,0,3]]
print a.take([[0,1],[0,1]])
# print a[[[0,1],[0,1]]] # これは出来ない
a = array([[10,20,30],[30,40,50]])
print a.take([0,2], axis=1)
print take(a, [0], axis=0)

[10 10 40]
[10 10 40]
[[10 20]
 [10 20]]
[[10 30]
 [30 50]]
[[10 20 30]]


In [95]:
# arg*
a = array([0,1,2,3,4,-4,-3,-2,-1])
print a.argmax()
print a.argmin()
print a.argsort()
a.resize((3,3))
print a
print a.argmax() # flatにしたときのargmaxらしい
print a.argmax(axis=0)
print a.argmax(axis=1)

4
5
[5 6 7 8 0 1 2 3 4]
[[ 0  1  2]
 [ 3  4 -4]
 [-3 -2 -1]]
4
[1 1 0]
[2 1 2]


In [100]:
# statistics
a = random.random((3,3))
print a
print cov(a)
print 'mean', a.mean()
print 'mean', a.mean(axis=1)
print 'std', a.std()
print 'std', a.std(axis=1)
print a.var()

[[ 0.83858984  0.91718714  0.96717936]
 [ 0.69874128  0.40576252  0.97576646]
 [ 0.8977384   0.10904858  0.22271307]]
[[ 0.004202    0.00684849 -0.02385129]
 [ 0.00684849  0.08124733  0.01814326]
 [-0.02385129  0.01814326  0.18176841]]
mean 0.67030296094
mean [ 0.90765211  0.69342342  0.40983335]
std 0.317730889675
std [ 0.05292764  0.23273351  0.34810765]
0.100952918254


In [101]:
# funcy indexing
a = arange(12) ** 2
i = array([1,1,3,8,5])
print a[i]
j = array([[3,4],[9,7]])
print a[j]

[ 1  1  9 64 25]
[[ 9 16]
 [81 49]]


In [106]:
# more than 2D array : referes 1st dimension
a = array([[0,0,0],[0,1,0],[2,0,0],[3,3,0]])
ind = array([[0,0,1,1],[3,0,1,2]])
print a[ind]

[[[0 0 0]
  [0 0 0]
  [0 1 0]
  [0 1 0]]

 [[3 3 0]
  [0 0 0]
  [0 1 0]
  [2 0 0]]]


In [108]:
# indices for more than one dimension
a = arange(12).reshape(3,4)
i = array([[0,1],[1,2]])
j = array([[2,1],[3,3]])
print a
print a[i,j]  # (0,2) (1,1) || (1,3) (2,3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  5]
 [ 7 11]]


In [110]:
# list-of-array is ok, but arrya-of-array is ng
l1 = [i,j]
l2 = array([i,j])
print a[l1]
# print a[l2] # this is err

[[ 2  5]
 [ 7 11]]


In [111]:
time = linspace(20, 145, 5)
data = sin(arange(20)).reshape(5,4)
ind = data.argmax(axis=0)
print ind
time_max = time[ind]
data_max = data[ind, xrange(data.shape[1])] # data[[ind[0],0],...] y軸を補っている
print time_max
print data_max
print all(data_max == data.max(axis=0))

[2 0 3 1]
[  82.5    20.    113.75   51.25]
[ 0.98935825  0.84147098  0.99060736  0.6569866 ]
True


In [113]:
#indexing with boolean arrays
a = arange(12).reshape(3,4)
b = a > 4
print a[b]
a[b] = 0
print a

[ 5  6  7  8  9 10 11]
[[0 1 2 3]
 [4 0 0 0]
 [0 0 0 0]]


In [116]:
# use slicing with boolean index
a = arange(12).reshape(3,4)
b1 = array([True, False, True])
b2 = array([False, True, False, True])
print a[b1,:]
print a[:,b2]
print a[b1, b2] # こういうことはしちゃいけないらしい

[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[ 1 11]


In [119]:
# ix_() function
a = array([2,3,4,5])
b = array([8,5,4])
c = array([5,4,6,8,3])
ax, bx, cx = ix_(a,b,c)
print ax.shape, bx.shape, cx.shape
result = ax + bx * cx
print result
print result[3,2,4]
print a[3]+b[2]*c[4]

(4, 1, 1) (1, 3, 1) (1, 1, 5)
[[[42 34 50 66 26]
  [27 22 32 42 17]
  [22 18 26 34 14]]

 [[43 35 51 67 27]
  [28 23 33 43 18]
  [23 19 27 35 15]]

 [[44 36 52 68 28]
  [29 24 34 44 19]
  [24 20 28 36 16]]

 [[45 37 53 69 29]
  [30 25 35 45 20]
  [25 21 29 37 17]]]
17
17


In [120]:
# check of ix_
print (bx * cx).shape
print (bx * cx) # indexがずれているので、b * c^T になるっぽい

(1, 3, 5)
[[[40 32 48 64 24]
  [25 20 30 40 15]
  [20 16 24 32 12]]]


In [122]:
# check of ix_ 2
d = array([[1],[2],[3]])
e = array([[3,4,5]])
print d
print e
print d + e
# 要素ごとの演算になるが、1+[3,4,5] で計算されるっぽい

[[1]
 [2]
 [3]]
[[3 4 5]]
[[4 5 6]
 [5 6 7]
 [6 7 8]]


In [131]:
def ufunc_reduce(ufct, *vectors):
    vs = ix_(*vectors)
    r = ufct.identity
    for v in vs:
        r = ufct(r,v)
    return r
print ufunc_reduce(add,a,b,c)
print '-----------------'
print ax + bx + cx

[[[15 14 16 18 13]
  [12 11 13 15 10]
  [11 10 12 14  9]]

 [[16 15 17 19 14]
  [13 12 14 16 11]
  [12 11 13 15 10]]

 [[17 16 18 20 15]
  [14 13 15 17 12]
  [13 12 14 16 11]]

 [[18 17 19 21 16]
  [15 14 16 18 13]
  [14 13 15 17 12]]]
-----------------
[[[15 14 16 18 13]
  [12 11 13 15 10]
  [11 10 12 14  9]]

 [[16 15 17 19 14]
  [13 12 14 16 11]
  [12 11 13 15 10]]

 [[17 16 18 20 15]
  [14 13 15 17 12]
  [13 12 14 16 11]]

 [[18 17 19 21 16]
  [15 14 16 18 13]
  [14 13 15 17 12]]]


In [132]:
# Record Arrays
img = array([(0,0,0),(1,0,0),(0,1,0),(0,0,1)], [('r',float32),('g',float32),('b', float32)])
print img
print img['r']

[(0.0, 0.0, 0.0) (1.0, 0.0, 0.0) (0.0, 1.0, 0.0) (0.0, 0.0, 1.0)]
[ 0.  1.  0.  0.]


In [134]:
# linear algebra
from numpy.linalg import *
a = array([[1.0,2.0],[3.0,4.0]])
print a.transpose()
print inv(a)
u = eye(2)
print dot(a,u)
print trace(u)
y = array([[5.],[7.]])
print solve(a,y)
lam, Lam = eig(a)
print lam
print Lam

[[ 1.  3.]
 [ 2.  4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 1.  2.]
 [ 3.  4.]]
2.0
[[-3.]
 [ 4.]]
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [136]:
# matrix
A = matrix('1.0 2.0; 3.0 4.0')
print A
print type(A)
print A.T
X = matrix('5.0 7.0')
Y = X.T
print A * Y
print A.I # inverse
print solve(A, Y)

[[ 1.  2.]
 [ 3.  4.]]
<class 'numpy.matrixlib.defmatrix.matrix'>
[[ 1.  3.]
 [ 2.  4.]]
[[ 19.]
 [ 43.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-3.]
 [ 4.]]


In [137]:
# NumPyはN-dimensional array と universal function以外はそれを元にして作っているので、
# matrixは2-dimensional arrayを継承しているらしい、
# matrix の indexには 2-d array用のindexの他、matrixも使えるとのこと
A = arange(12)
A.shape = 3,4
M = mat(A.copy())
print type(A)
print A
print M

<type 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [138]:
print A[:];
print A[:].shape
print M[:]
print M[:].shape

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [139]:
print A[:,1]
print A[:,1].shape
print M[:,1]
print M[:,1].shape # columnの形を保ったままにできる
print M

[1 5 9]
(3,)
[[1]
 [5]
 [9]]
(3, 1)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [140]:
print A[1,:]
print M[1,:]

[4 5 6 7]
[[4 5 6 7]]


In [144]:
# Aから1st and 3rd columnを切り出す方法
print A[:,[1,3]]
print A.take([1,3], axis=1)
print A[1:,].take([1,3], axis=1) # 1st rowを飛ばす

[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 5  7]
 [ 9 11]]


In [146]:
# use ix_
print A[ix_((1,2),(1,3))]

[[ 5  7]
 [ 9 11]]


In [147]:
# 始めのrowが1より大きいcolumnを取り出す
print A[:,A[0,:]>1]

[[ 2  3]
 [ 6  7]
 [10 11]]


In [148]:
# Matrixで同じようなことしようとすると、sliceが Matrixになってこける
print M[:,M[0,:]>1]

[[2 3]]


In [149]:
# ので、 .Aという属性を使って乗り切る
print M[:,M.A[0,:]>1]

[[ 2  3]
 [ 6  7]
 [10 11]]


In [150]:
#  row とcolumnの両方の条件で取り出したい時は
print A[A[:,0]>2,A[0,:]>1] # やったらあかんやーつ
print A[ix_(A[:,0]>2, A[0,:]>1)]

[ 6 11]
[[ 6  7]
 [10 11]]


In [153]:
# Tricks and Tips
# auto reshape
a = arange(30)
a.shape = 2, -1, 3 # -1 means 必要な値を適当に入れて
print a.shape
print a

(2, 5, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [156]:
# vector stacking
# matlabだと[x;y] とか[x,y]とかで出来るように、stackで出来るの良いよね;-) ということらしい
x = arange(0,10,2)
y = arange(5)
m = vstack([x,y])
xy = hstack([x,y])
print m
print xy

[[0 2 4 6 8]
 [0 1 2 3 4]]
[0 2 4 6 8 0 1 2 3 4]
